/// <reference types="next" />
/// <reference types="next/image-types/global" />

// NOTE: this file is normally generated by `next dev` / `next build`. It is
// stubbed here so tsconfig.json resolves; this starter does not run the real
// Next.js toolchain (no `npm install` was performed — see README.md). It is
// excluded from tsconfig.build.json, the config actually used for offline
// verification, so its unmet `next` type reference never gets type-checked.
