#!/usr/bin/env bash
# gen_manifest.sh — derives manifest.json straight from the module graph.
#
# Nothing here is hand-authored: "capabilities" comes from scanning
# core.pas's own function/procedure declarations, and "edges" comes from
# scanning every file's `uses` clause. Run `make manifest` to regenerate
# manifest.json after changing src/*.pas; tools/check_manifest_drift.sh is
# the CI-facing check that fails if you forgot to.
set -euo pipefail
cd "$(dirname "$0")/.."
# shellcheck source=./lib_graph.sh
source tools/lib_graph.sh

CORE_FILE="$SRC_DIR/core.pas"

echo "{"
echo '  "_comment": "GENERATED by tools/gen_manifest.sh from src/*.pas — do not hand-edit. Run `make manifest`.",'

echo '  "capabilities": {'
first=1
while IFS= read -r prim; do
  [ -z "$prim" ] && continue
  if [ "$first" -eq 0 ]; then echo ","; fi
  printf '    "%s": "%s"' "$prim" "$CORE_FILE"
  first=0
done < <(primitives_of "$CORE_FILE")
echo ""
echo "  },"

echo '  "modules": {'
first=1
for f in $(list_src_files); do
  self="$(unit_name_of "$f")"
  [ -z "$self" ] && continue
  kind="$(classify "$f")"
  if [ "$first" -eq 0 ]; then echo ","; fi
  printf '    "%s": {"file": "%s", "kind": "%s"}' "$self" "$f" "$kind"
  first=0
done
echo ""
echo "  },"

echo '  "edges": ['
first=1
for f in $(list_src_files); do
  self="$(unit_name_of "$f")"
  [ -z "$self" ] && continue
  while IFS= read -r used; do
    [ -z "$used" ] && continue
    if [ "$first" -eq 0 ]; then echo ","; fi
    printf '    {"from": "%s", "to": "%s", "file": "%s"}' "$self" "$used" "$f"
    first=0
  done < <(uses_of "$f")
done
echo ""
echo "  ]"
echo "}"
